/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Brokoth
 */
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.Timestamp;

import java.util.logging.Level;
import java.util.logging.Logger;
public class SocketClient extends javax.swing.JFrame {
    static ServerSocket ss;
    static Socket s;
    static DataInputStream dis;
    static DataOutputStream dos;
    /**
     * Creates new form client_form
     */
    public SocketClient() {
        initComponents();
    }
  public SocketClient(String Thanks) {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toy_details_lbl = new javax.swing.JLabel();
        manufacturer_getails_lbl = new javax.swing.JLabel();
        toy_code_lbl = new javax.swing.JLabel();
        toy_name_lbl = new javax.swing.JLabel();
        toy_price_lbl = new javax.swing.JLabel();
        mf_date_lbl = new javax.swing.JLabel();
        toy_batch_no_lbl = new javax.swing.JLabel();
        toy_desc_lbl = new javax.swing.JLabel();
        toy_code_textfield = new javax.swing.JTextField();
        toy_name_textfield = new javax.swing.JTextField();
        toy_price_textfield = new javax.swing.JTextField();
        toy_manufacture_date_textfield = new javax.swing.JTextField();
        toy_batch_no_textfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        toy_description_textarea = new javax.swing.JTextArea();
        submit_btn = new javax.swing.JButton();
        company_name_lbl = new javax.swing.JLabel();
        street_address_lbl = new javax.swing.JLabel();
        zip_code_lbl = new javax.swing.JLabel();
        country_lbl = new javax.swing.JLabel();
        company_name_textfield = new javax.swing.JTextField();
        street_address_textfield = new javax.swing.JTextField();
        zip_code_textfield = new javax.swing.JTextField();
        country_textfield = new javax.swing.JTextField();
        toy_form_lbl = new javax.swing.JLabel();
        thanks_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        server_msg = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toy_details_lbl.setText("TOY DETAILS");

        manufacturer_getails_lbl.setText("MANUFACTURER DETAILS");

        toy_code_lbl.setText("CODE");

        toy_name_lbl.setText("NAME");

        toy_price_lbl.setText("PRICE");

        mf_date_lbl.setText("MANUFACTURE DATE");

        toy_batch_no_lbl.setText("BATCH NO.");

        toy_desc_lbl.setText("DESCRIPTION");

        toy_code_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toy_code_textfieldActionPerformed(evt);
            }
        });

        toy_name_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toy_name_textfieldActionPerformed(evt);
            }
        });

        toy_description_textarea.setColumns(20);
        toy_description_textarea.setRows(5);
        jScrollPane1.setViewportView(toy_description_textarea);

        submit_btn.setText("SUBMIT");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        company_name_lbl.setText("COMPANY NAME");

        street_address_lbl.setText("STREET ADDRESS");

        zip_code_lbl.setText("ZIP-CODE");

        country_lbl.setText("COUNTRY");

        company_name_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                company_name_textfieldActionPerformed(evt);
            }
        });

        country_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                country_textfieldActionPerformed(evt);
            }
        });

        toy_form_lbl.setText("CLIENT FORM");

        thanks_btn.setText("THANK THE SERVER");
        thanks_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thanks_btnActionPerformed(evt);
            }
        });

        server_msg.setColumns(20);
        server_msg.setRows(5);
        jScrollPane2.setViewportView(server_msg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(toy_code_textfield)
                            .addComponent(toy_name_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(toy_price_textfield)
                            .addComponent(toy_manufacture_date_textfield)
                            .addComponent(toy_batch_no_textfield)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(toy_details_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(country_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(zip_code_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(street_address_lbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(company_name_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zip_code_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(country_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(street_address_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(company_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(manufacturer_getails_lbl)
                        .addGap(72, 72, 72))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(submit_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(toy_form_lbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(thanks_btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(toy_name_lbl)
                            .addComponent(toy_price_lbl)
                            .addComponent(mf_date_lbl)
                            .addComponent(toy_batch_no_lbl)
                            .addComponent(toy_desc_lbl)
                            .addComponent(toy_code_lbl))
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toy_form_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(thanks_btn)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturer_getails_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toy_details_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toy_code_lbl)
                    .addComponent(toy_code_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toy_name_lbl)
                    .addComponent(toy_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(company_name_lbl)
                    .addComponent(company_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toy_price_lbl)
                    .addComponent(toy_price_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(street_address_lbl)
                    .addComponent(street_address_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mf_date_lbl)
                    .addComponent(toy_manufacture_date_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zip_code_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zip_code_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toy_batch_no_lbl)
                    .addComponent(toy_batch_no_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(country_lbl)
                    .addComponent(country_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toy_desc_lbl))
                .addGap(18, 18, 18)
                .addComponent(submit_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toy_code_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toy_code_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toy_code_textfieldActionPerformed

    private void toy_name_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toy_name_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toy_name_textfieldActionPerformed

    private void company_name_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_company_name_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_company_name_textfieldActionPerformed

    private void country_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_country_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_country_textfieldActionPerformed

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
        String toy_name = toy_name_textfield.getText();
        String toy_price = toy_price_textfield.getText();
        String toy_code = toy_code_textfield.getText();
        String toy_batch_no = toy_batch_no_textfield.getText();
        String toy_mf_date = toy_manufacture_date_textfield.getText();
        String toy_desc = toy_description_textarea.getText();
        String company_name = company_name_textfield.getText();
        String country = country_textfield.getText();
        String street_address = street_address_textfield.getText();
        String zip_code = zip_code_textfield.getText();
        String all_details = "Toy Name: "+toy_name+" Toy Price: "+toy_price+
               " Toy Code: "+toy_code+" Toy Batch No: "+toy_batch_no
               +" Toy Manufacture Date: "+toy_mf_date+" Toy Description: "+toy_desc
               +" Company Name: "+company_name+" Country: "+country+" Street Address: "
               +street_address+" Zip Code: "+zip_code;
      
        try {
            dos.writeUTF(all_details);
            toy_name_textfield.setText("");
            toy_price_textfield.setText("");
            toy_code_textfield.setText("");
            toy_batch_no_textfield.setText("");
            toy_manufacture_date_textfield.setText("");
            toy_description_textarea.setText("");
            company_name_textfield.setText("");
            country_textfield.setText("");
            street_address_textfield.setText("");
            zip_code_textfield.setText("");
        } catch (IOException ex) {
            Logger.getLogger(SocketClient.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        
    }//GEN-LAST:event_submit_btnActionPerformed

    private void thanks_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thanks_btnActionPerformed
        // TODO add your handling code here:
 Timestamp now = new Timestamp(new java.util.Date().getTime());
             try {
            dos.writeUTF("Thanks! " +now.toString());
        } catch (IOException ex) {
            Logger.getLogger(SocketClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_thanks_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SocketClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SocketClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SocketClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SocketClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SocketClient().setVisible(true);
                
            }
        });
        s = new Socket("localhost",3333);
        dis = new DataInputStream(s.getInputStream());
        dos = new DataOutputStream(s.getOutputStream());
        String msgin = "";
        while(!msgin.equals("stop")){
        msgin = dis.readUTF();
        ClientProtocol cp = new ClientProtocol();
        msgin = cp.messageHandler(msgin);
     server_msg.setText(server_msg.getText()
                .trim()+"\n"+msgin);
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel company_name_lbl;
    private javax.swing.JTextField company_name_textfield;
    private javax.swing.JLabel country_lbl;
    private javax.swing.JTextField country_textfield;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel manufacturer_getails_lbl;
    private javax.swing.JLabel mf_date_lbl;
    private static javax.swing.JTextArea server_msg;
    private javax.swing.JLabel street_address_lbl;
    private javax.swing.JTextField street_address_textfield;
    private javax.swing.JButton submit_btn;
    private javax.swing.JButton thanks_btn;
    private javax.swing.JLabel toy_batch_no_lbl;
    private javax.swing.JTextField toy_batch_no_textfield;
    private javax.swing.JLabel toy_code_lbl;
    private javax.swing.JTextField toy_code_textfield;
    private javax.swing.JLabel toy_desc_lbl;
    private javax.swing.JTextArea toy_description_textarea;
    private javax.swing.JLabel toy_details_lbl;
    private javax.swing.JLabel toy_form_lbl;
    private javax.swing.JTextField toy_manufacture_date_textfield;
    private javax.swing.JLabel toy_name_lbl;
    private javax.swing.JTextField toy_name_textfield;
    private javax.swing.JLabel toy_price_lbl;
    private javax.swing.JTextField toy_price_textfield;
    private javax.swing.JLabel zip_code_lbl;
    private javax.swing.JTextField zip_code_textfield;
    // End of variables declaration//GEN-END:variables
}
